[workspace]
members = [".", "crates/*"]
resolver = "2"

[package]
name = "flap"
version = "0.0.6"
edition = "2024"

[[bin]]
name = "generate_dart"
path = "src/bin/generate_dart.rs"

[dependencies]
flap-ir = { path = "crates/flap-ir" }
flap-emit-dart = { path = "crates/flap-emit-dart" }
flap-spec = { path = "crates/flap-spec" }
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"
